project_id = "lddfufxcrnqixfiyhrvc"

[functions.delete-user]
verify_jwt = true

[functions.telegram-bot-webhook]
verify_jwt = false

[functions.setup-telegram-webhook]
verify_jwt = false

[functions.hash-password]
verify_jwt = false

[functions.verify-password]
verify_jwt = false
