name: Keep Supabase Awake

on:
  schedule:
    - cron: '0 7 * * *'  # Roda todos os dias às 7h UTC
  workflow_dispatch:      # Permite execução manual

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Supabase endpoint
        run: |
          curl -I https://<SUA-URL>.supabase.co/rest/v1/<NOME-TABELA>
